# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
    core: ren/circleci-orbs@dev:first

executors:
  default:
    docker:
      - image: circleci/node:8.15
    working_directory: ~/swapperd-desktop

commands:
  install_deps:
    description: "Install dependencies"
    steps:
      - core/install_wine
      # Download and cache dependencies
      - restore_cache:
          name: Restore node_modules
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          name: Save node_modules
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  release:
    description: Makes a release to Github
    parameters:
      prerelease:
        description: Whether the release should be a prerelease or not
        type: boolean
        default: false
    steps:
      - run:
          name: Deploying to Releases
          command: <<# parameters.prerelease >>EP_PRE_RELEASE="true"<</ parameters.prerelease >> GH_TOKEN="${GITHUB_TOKEN}" yarn run release

jobs:
  prerelease:
    executor: default
    steps:
      - checkout
      - install_deps
      - release:
          prerelease: true
  release:
    executor: default
    steps:
      - checkout
      - install_deps
      - release
  build:
    executor: default
    steps:
      - checkout
      - install_deps
      - run:
          name: Build
          command: yarn run build:all
      - run:
          name: Run tests
          command: yarn test

workflows:
  build:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only:
                - stable
      - prerelease:
          requires:
            - build
          filters:
            branches:
              only:
                - nightly
#  nightly:
#    triggers:
#      - schedule:
#          cron: "0 2 * * *" # every night at 02:00
#          filters:
#            branches:
#              only:
#                - master
#    jobs:
#      - core/merge_nightly:
#          executor: default
#  monthly:
#    triggers:
#      - schedule:
#          cron: "0 0 1 * *" # on the 1st of every month at 00:00
#          filters:
#            branches:
#              only:
#                - master
#    jobs:
#      - core/merge_stable:
#          executor: default
#      - core/merge_beta:
#          executor: default
#          # Only run merge_beta after merge_stable is run
#          requires:
#            - core/merge_stable
