# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
    core: ren/circleci-orbs@dev:first

executors:
  default_exec:
    docker:
      - image: circleci/node:8.15
    working_directory: ~/swapperd-desktop

commands:
  install_deps:
    description: "Install dependencies"
    steps:
      - run:
          name: Install Wine
          command: |-
            sudo dpkg --add-architecture i386
            sudo apt-get update
            sudo apt-get install --no-install-recommends --assume-yes wine wine32
      # Download and cache dependencies
      - restore_cache:
          name: Restore node_modules
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          name: Save node_modules
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

jobs:
  release:
    executor: default_exec
    steps:
      - checkout
      - install_deps
      - run:
          name: Deploying to Releases
          command: |-
            GH_TOKEN="${GITHUB_TOKEN}" yarn run release
  build:
    executor: default_exec
    steps:
      - checkout
      - install_deps
      - run:
          name: Build
          command: yarn run build:all
      - run:
          name: Run tests
          command: yarn test

workflows:
  build:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only:
                - stable
  nightly:
    triggers:
      - schedule:
          cron: "0 2 * * *" # every night at 02:00
          filters:
            branches:
              only:
                - master
    jobs:
      - core/merge_nightly:
          executor: default_exec
  monthly:
    triggers:
      - schedule:
          cron: "0 0 1 * *" # on the 1st of every month at 00:00
          filters:
            branches:
              only:
                - master
    jobs:
      - core/merge_stable:
          executor: default_exec
      - core/merge_beta:
          executor: default_exec
          # Only run merge_beta after merge_stable is run
          requires:
            - core/merge_stable
