# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

_defaults: &defaults
    docker:
      - image: circleci/node:8.15
    working_directory: ~/swapperd-desktop

commands:
  rw_checkout:
    description: "Checkout with Read/Write Privileges"
    steps:
      - run:
          name: Setup Git
          command: |
            pwd
            RW_REPO_URL="https://${GITHUB_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"
            echo ${CIRCLE_WORKING_DIRECTORY}
            eval echo ${CIRCLE_WORKING_DIRECTORY}

            if [ -e $(eval echo ${CIRCLE_WORKING_DIRECTORY})/.git ]
            then
              cd $(eval echo ${CIRCLE_WORKING_DIRECTORY})
              git remote set-url origin "${RW_REPO_URL}" || true
              git fetch --force origin "master:remotes/origin/master"
            else
              mkdir -p $(eval echo ${CIRCLE_WORKING_DIRECTORY})
              cd $(eval echo ${CIRCLE_WORKING_DIRECTORY})
              git clone ${RW_REPO_URL} .
            fi
            pwd
            git fetch --all
  merge:
    description: "Merge from branch into another branch"
    parameters:
      from:
        description: The branch with changes to be merged into another branch
        type: string
      into:
        description: The branch onto which changes will be applied
        type: string
    steps:
      - rw_checkout
      - run:
          name: Merging branch
          command: |
            pwd
            git reset --hard
            git checkout --track origin/<< parameters.into >>
            git merge origin/<< parameters.from >> -v
            git push

jobs:
  merge_nightly:
    <<: *defaults
    steps:
      - merge:
          from: master
          into: nightly
  merge_beta:
    <<: *defaults
    steps:
      - merge:
          from: nightly
          into: beta
  merge_stable:
    <<: *defaults
    steps:
      - merge:
          from: beta
          into: stable
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install Wine
          command: |-
            sudo dpkg --add-architecture i386
            sudo apt-get update
            sudo apt-get install --no-install-recommends --assume-yes wine wine32

      # Download and cache dependencies
      - restore_cache:
          name: Restore node_modules
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Build
          command: yarn run build:all
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          name: Save node_modules
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: Run tests
          command: yarn test

workflows:
  version: 2.1
  build:
    jobs:
    - build
    - merge_nightly
  nightly:
    triggers:
      - schedule:
          cron: "0 2 * * *" # every night at 02:00
          filters:
            branches:
              only:
                - master
    jobs:
      - merge_nightly:
          filters:
            branches:
              only: master
  monthly:
    triggers:
      - schedule:
          cron: "0 0 1 * *" # on the 1st of every month at 00:00
          filters:
            branches:
              only:
                - master
    jobs:
      - merge_stable:
          filters:
            branches:
              only: master
      - merge_beta:
          filters:
            branches:
              only: master
          # Only run merge_beta after merge_stable is run
          requires:
            - merge_stable
